
scenario:
  clusters:
  - 33
  opts:
  - ''
  sector_opts:
  - ''
  planning_horizons:
  - 2050
  
countries:
    - AT
    - BE
    - BG
    - CH
    - CZ
    - DE
    - DK
    - EE
    - ES
    - FI
    - FR
    - GB
    - GR
    - HR
    - HU
    - IE
    - IT
    - LT
    - LU
    - LV
    - NL
    - "NO"
    - PL
    - PT
    - RO
    - SE
    - SI
    - SK
    
lines:
  max_extension: 15000 #MW
  
links:
  max_extension: 25000 #MW

industry:
    heat_via_biomass: false
    
    
electricity: # consider nuclear capacitiy expansion everwhere and limit it in the custom constraints
  extendable_carriers:
    Generator: [solar, solar-hsat, onwind, offwind-ac, offwind-dc, offwind-float, OCGT, CCGT,nuclear]
  everywhere_powerplants: [nuclear]
  
  
sector:

  land_transport_fuel_cell_share:
    2050: 0.1874
    
  land_transport_electric_share:
    2050: 0.7898
    
  land_transport_ice_share:
    2050: 0.0228
    
  shipping_methanol_share:
    2050: 0
    
  shipping_oil_share:
    2050: 1
    
  regional_co2_sequestration_potential:
    enable: true
    attribute:
    - conservative estimate Mt

  biomass_spatial: true #if biomass is spatial, the synfuel production may happen in place in all the countries
  biomass_transport: true # in this case it can move wiht a cost
  biomass_to_liquid: false
  biomass_to_liquid_cc: true
  electrobiofuels: false

  H2_network: true
  H2_retrofit: false
  methanol:
    methanol_to_power:
      ccgt: false
      ccgt_cc: false
      ocgt: false
      allam: false
      
  # this is also fueling a bit the crazy growth of district heating. Let's assume they cant contribute to district heating at this stage
  use_fischer_tropsch_waste_heat: false
  use_haber_bosch_waste_heat: false
  use_methanolisation_waste_heat: false
  use_methanation_waste_heat: false
  use_fuel_cell_waste_heat: false
  use_electrolysis_waste_heat: false
  co2_sequestration_potential:
    2050: 266
  district_heating:
    potential:
        default: 0 # keep the district_heating as it is today,
        AL: 0.0
        AT: 0.14
        BA: 0.08
        BE: 0.008
        BG: 0.16
        CH: 0.04
        CZ: 0.167
        DE: 0.079
        DK: 0.5
        EE: 0.4
        ES: 0.0
        FI: 0.39
        FR: 0.05
        FR: 0.05
        GB: 0.02
        GR: 0.01
        HR: 0.07
        HU: 0.08
        IE: 0.0
        IT: 0.03
        LT: 0.4
        LU: 0.1
        LV: 0.33
        ME: 0.0
        MK: 0.25
        NL: 0.04
        "NO" : 0.04
        PL: 0.2
        PT: 0.001
        RO: 0.11
        RS: 0.26
        SE: 0.42
        SI: 0.1
        SK: 0.15
        XK: 0.03
        
  imports:
    enable: true
    # limit: 10000000000

    limit_sense: <=
    price:
      NH3: 97
      # methanol: 121
      oil: 125
      
  methanol:
    methanol_reforming: false
    methanol_reforming_cc: false
    
# adding custom constraints
solving:
  # solver:
  #   name: gurobi
  #   options: gurobi-numeric-focus
    
  options:
    curtailment_mode: false
  constraints:
  
    min_cap_constraint:
        enable: true
        path: "data/additional_data/min_cap_2050_DE.csv"
        ratio: 0.75
        countries: "all"
            # - AT
            # - BE
            # - BG
            # - CH
            # - CZ
            # - DE
            # - DK
            # - EE
            # - ES
            # - FI
            # - FR
            # - GB
            # - GR
            # - HR
            # - HU
            # - IE
            # - IT
            # - LT
            # - LU
            # - LV
            # - NL
            # - "NO"
            # - PL
            # - PT
            # - RO
            # - SE
            # - SI
            # - SK
        nuclear: true
  
    oil_supply_constraint:
        enable: true
        path: "data/additional_data/liquid_supply.csv"

    import_tax:
        enable: true
        electricity: 
            tax_value: 20 #eur/mwh
            max_import_share: 0.3 #if import is more than the max_import_share * demand will be taxed
        hydrogen: 
            tax_value: 20 #eur/mwh
            max_import_share: 0.75 #if import is more than the max_import_share * demand will be taxed
      
    firm_capacity:
        enable: true
        max_demand_hour_share: 1 # percentage of max hour demand to be met by firm carriers
        capacity_shares: # the list of firm carriers, and share of their capacity to contribute to max hour demand
            "OCGT": 0.9
            "CCGT": 0.9
            # "OCGT methanol": 0.9
            "nuclear": 0.9
            "H2 turbine": 0.9
            "H2 Fuel Cell": 0.9
            "hydro": 0.9
            "PHS": 0.5
            "battery": 0.5
            "home battery": 0.5
            
    overwrite_technical_potentials: true
    import_constraints:
        sense: ">="
        carriers: 
            NH3: 893520000 # 612 TWh * 1.46 (efficiency of ammonia cracker)
            oil: 152000000
clustering:
  temporal:
    resolution_sector: 3h
    
snapshots:
  start: "2013-01-01"
  end: "2014-01-01"
  inclusive: 'left'


  capital_cost:
    "HVDC inverter pair": 215543.95174 # 165803.0398*1.3
    "HVDC overhead": 574.78382 # 442.1414*1.3
    "HVDC submarine": 1310.78142 # 1008.2934*1.3
    "HVDC underground": 1310.78142 # 1008.2934*1.3
    


